[package]
name = "sample"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neovim-lib = { version = "0.6.1" }
open = { version = "4.1.0" }
reqwest = { version = "0.11", features = ["json"] }
